name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: advisor
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client & run migrations
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/advisor
        run: |
          npx prisma generate
          npx prisma migrate deploy

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/advisor
          NODE_ENV: test
        run: npm test -- --runInBand
